# build image using docker file the '.' builds and search from the same directory
build-image:

	docker build -t chatbud .

#
run-image:
	docker run -p 3000:3000 chatbud 

# -d for detaiched mode
build-compose:
	docker-compose up -d 

# If you want to use mongodb atlas remove mongo-db service from docker-compose and add atlas url in the environment 
# You should also remove the depends on from the chatbud service